--- Makefile.org	2009-11-15 07:56:22.000000000 -0800
+++ Makefile	2010-02-05 13:38:34.250656525 -0800
@@ -55,7 +55,7 @@
 
 COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
 ssp_gen.o getmags.o gasdev.o spline.o splint.o ran.o ran_state.o \
-locate.o qromb.o polint.o trapzd.o tridag.o sps_setup.o	ran2.o	 \
+locate.o qromb.o polint.o galacticus_IMF.o trapzd.o tridag.o sps_setup.o ran2.o	 \
 pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
 add_bs.o mod_hb.o add_remnants.o getindx.o velbroad.o mod_agb.o
 
