--- Makefile	2013-11-29 10:17:07.000000000 -0800
+++ Makefile.1	2013-11-29 10:18:11.000000000 -0800
@@ -47,7 +47,7 @@
 PROGS = simple lesssimple autosps 
 
 COMMON = sps_vars.o sps_utils.o compsp.o ssp_gen.o getmags.o locate.o funcint.o \
-sps_setup.o pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
+sps_setup.o galacticus_IMF.o pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
 add_bs.o mod_hb.o add_remnants.o getindx.o smoothspec.o mod_gb.o \
 write_isochrone.o sfhstat.o linterp.o tsum.o add_agb_dust.o linterparr.o
 
