*** Makefile.orig	2013-06-14 07:17:04.000000000 -0700
--- Makefile	2013-06-14 07:18:40.000000000 -0700
*************** F90FLAGS = -O -cpp
*** 47,53 ****
  PROGS = simple lesssimple autosps 
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
! ran_state.o ssp_gen.o getmags.o myran.o ran1.o locate.o qromb.o polint.o trapzd.o \
  sps_setup.o pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o smoothspec.o mod_gb.o \
  write_isochrone.o sfhstat.o linterp.o init_random_seed.o tsum.o
--- 47,53 ----
  PROGS = simple lesssimple autosps 
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
! ran_state.o ssp_gen.o getmags.o myran.o ran1.o locate.o qromb.o polint.o galacticus_IMF.o trapzd.o \
  sps_setup.o pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o smoothspec.o mod_gb.o \
  write_isochrone.o sfhstat.o linterp.o init_random_seed.o tsum.o
