*** Makefile.orig	2011-09-29 09:28:47.926299557 -0700
--- Makefile	2011-09-29 09:28:48.671290243 -0700
***************
*** 48,54 ****
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
  ssp_gen.o getmags.o gasdev.o spline.o splint.o ran.o ran_state.o \
! locate.o qromb.o polint.o trapzd.o tridag.o sps_setup.o	ran2.o	 \
  pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o velbroad.o mod_agb.o \
  write_isochrone.o sfhstat.o
--- 48,54 ----
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
  ssp_gen.o getmags.o gasdev.o spline.o splint.o ran.o ran_state.o \
! locate.o qromb.o polint.o galacticus_IMF.o trapzd.o tridag.o sps_setup.o	ran2.o	 \
  pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o velbroad.o mod_agb.o \
  write_isochrone.o sfhstat.o
