*** Makefile.orig	2011-12-19 08:34:01.000000000 -0800
--- Makefile	2011-12-19 08:35:36.611926144 -0800
***************
*** 47,53 ****
  PROGS = simple lesssimple autosps 
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
! ssp_gen.o getmags.o ran.o locate.o qromb.o polint.o trapzd.o tridag.o \
  sps_setup.o pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o velbroad.o mod_agb.o \
  write_isochrone.o sfhstat.o linterp.o
--- 47,53 ----
  PROGS = simple lesssimple autosps 
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
! ssp_gen.o getmags.o ran.o locate.o qromb.o polint.o galacticus_IMF.o trapzd.o tridag.o \
  sps_setup.o pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o velbroad.o mod_agb.o \
  write_isochrone.o sfhstat.o linterp.o
