#!/usr/bin/env python3
"""Generate reference values for the splashback radius models using the Colossus toolkit
(https://bdiemer.bitbucket.io/colossus/). The resulting tables are used by the
`tests.splashback_radii.exe` unit test to validate Galacticus' implementations of these models.

Run as:

    python3 testSuite/data/splashbackRadiiColossus/generate.py

Requires `colossus` to be installed (`pip install colossus`). The output files are committed to
the repository, so this script only needs to be re-run if the models, or the sampled grid, change.
"""
import os

from colossus.cosmology import cosmology
from colossus.halo import splashback

COSMOLOGY = 'planck18'
REDSHIFTS = [0.0, 0.5, 1.0, 2.0, 4.0, 8.0]
GAMMAS = [0.5, 1.0, 2.0, 3.0, 5.0]
PEAK_HEIGHTS = [0.5, 1.0, 2.0, 3.0, 4.0]
# Splashback definitions, in the order of the `splashbackDefinition` enumeration in Galacticus.
DEFINITIONS = ['sp-apr-mn', 'sp-apr-p50', 'sp-apr-p75', 'sp-apr-p87', 'sp-apr-p90']

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    cosmo = cosmology.setCosmology(COSMOLOGY)
    omegas = [(z, cosmo.Om(z)) for z in REDSHIFTS]

    for model in ('diemer17', 'diemer20'):
        rows = []
        for iDefinition, definition in enumerate(DEFINITIONS, start=1):
            for z, omegaMatter in omegas:
                for nu in PEAK_HEIGHTS:
                    for gamma in GAMMAS:
                        args = (gamma, nu, z, definition)
                        radius = splashback.modelDiemerRspMsp(
                            *args, splashback._modelDiemerGetPars(model, 'RspR200m', definition))
                        mass = splashback.modelDiemerRspMsp(
                            *args, splashback._modelDiemerGetPars(model, 'MspM200m', definition))
                        scatterRadius = splashback.modelDiemerScatter(
                            gamma, nu, definition,
                            splashback._modelDiemerGetPars(model, 'RspR200m-1s', definition))
                        scatterMass = splashback.modelDiemerScatter(
                            gamma, nu, definition,
                            splashback._modelDiemerGetPars(model, 'MspM200m-1s', definition))
                        # Colossus applies the floor on the scatter in `splashbackModel()` rather
                        # than in `modelDiemerScatter()`; apply it here to match.
                        scatterRadius = max(scatterRadius, 0.02)
                        scatterMass = max(scatterMass, 0.02)
                        rows.append((iDefinition, gamma, nu, omegaMatter,
                                     radius, mass, scatterRadius, scatterMass))
        write(model + '.txt', rows,
              'Reference values for the %s splashback model, from Colossus (cosmology: %s).'
              % (model, COSMOLOGY),
              ['definition', 'Gamma', 'nu200m', 'OmegaMatter',
               'RspR200m', 'MspM200m', 'sigmaRsp', 'sigmaMsp'])

    rows = []
    for _, omegaMatter in omegas:
        for gamma in GAMMAS:
            rows.append((gamma, omegaMatter,
                         splashback.modelShi16RspR200m(gamma, omegaMatter),
                         splashback.modelShi16Delta(gamma, omegaMatter)))
    write('shi2016.txt', rows,
          'Reference values for the shi16 splashback model, from Colossus (cosmology: %s).'
          % COSMOLOGY,
          ['s', 'OmegaMatter', 'RspR200m', 'Deltasp'])


def write(name, rows, title, columns):
    path = os.path.join(HERE, name)
    with open(path, 'w') as f:
        f.write('# %s\n' % title)
        f.write('# Generated by testSuite/data/splashbackRadiiColossus/generate.py\n')
        f.write('# Columns: %s\n' % ' '.join(columns))
        for row in rows:
            f.write(' '.join(('%d' % v) if isinstance(v, int) else ('%22.15e' % v)
                             for v in row) + '\n')
    print('wrote %s (%d rows)' % (path, len(rows)))


if __name__ == '__main__':
    main()
