!! Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
!!           2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026
!!    Andrew Benson <abenson@carnegiescience.edu>
!!
!! This file is part of Galacticus.
!!
!!    Galacticus is free software: you can redistribute it and/or modify
!!    it under the terms of the GNU General Public License as published by
!!    the Free Software Foundation, either version 3 of the License, or
!!    (at your option) any later version.
!!
!!    Galacticus is distributed in the hope that it will be useful,
!!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!    GNU General Public License for more details.
!!
!!    You should have received a copy of the GNU General Public License
!!    along with Galacticus.  If not, see <http://www.gnu.org/licenses/>.

!+    Contributions to this file made by: Andrew Benson, Claude.

!!{RST
Contains a module which enforces the bounds declared for input parameters.
!!}

module Input_Parameters_Bounds
  !!{RST
  Enforces the bounds declared (by ``<minimum>`` and ``<maximum>`` elements) in ``inputParameter`` directives. Calls to
  ``inputParameterBoundCheck`` are generated by the build system, following the reading of each parameter which declares
  a bound.
  !!}
  use :: Kind_Numbers, only : kind_int8
  implicit none
  private
  public :: inputParameterBoundCheck

  interface inputParameterBoundCheck
     module procedure inputParameterBoundCheckInteger
     module procedure inputParameterBoundCheckLong
     module procedure inputParameterBoundCheckDouble
  end interface inputParameterBoundCheck

  ! Generic type instances used to generate the type-specific bound checks.
  !![
  <generic identifier="valuetype">
   <instance label="Integer" intrinsic="integer"                   format="(i0)"   />
   <instance label="Long"    intrinsic="integer(kind=kind_int8)"   format="(i0)"   />
   <instance label="Double"  intrinsic="double precision"          format="(e12.6)"/>
  </generic>
  !!]

contains

  subroutine inputParameterBoundCheck{valuetype¦label}(parameters,name,value,bound,boundText,isMinimum,isInclusive)
    !!{RST
    Check that the ``value`` of the input parameter ``name`` (read from ``parameters``) respects the given ``bound`` (a minimum
    if ``isMinimum`` is true, otherwise a maximum, which the value may equal if ``isInclusive`` is true), and report a fatal
    error if it does not. ``boundText`` is the bound as declared, for use in the error message.
    !!}
    use :: Error             , only : Error_Report
    use :: Input_Parameters  , only : inputParameters
    use :: ISO_Varying_String, only : char
    implicit none
    class           (inputParameters      ), intent(in   ), target :: parameters
    character       (len=*                ), intent(in   )         :: name       , boundText
    {valuetype¦intrinsic}                  , intent(in   )         :: value
    double precision                       , intent(in   )         :: bound
    logical                                , intent(in   )         :: isMinimum  , isInclusive
    logical                                                        :: isViolated
    character       (len=32               )                        :: valueText
    character       (len=24               )                        :: relation

    if (isMinimum) then
       if (isInclusive) then
          isViolated=value <  bound
          relation  ='greater than or equal to'
       else
          isViolated=value <= bound
          relation  ='greater than'
       end if
    else
       if (isInclusive) then
          isViolated=value >  bound
          relation  ='less than or equal to'
       else
          isViolated=value >= bound
          relation  ='less than'
       end if
    end if
    if (.not.isViolated) return
    write (valueText,'{valuetype¦format}') value
    call Error_Report(                                                                                        &
         &            'parameter ['//char(parameters%path())//name//'] has value '//trim(adjustl(valueText))// &
         &            ', but must be '//trim(relation)//' '//boundText                                     // &
         &            {introspection:location}                                                                &
         &           )
    return
  end subroutine inputParameterBoundCheck{valuetype¦label}

end module Input_Parameters_Bounds
