!! Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
!!           2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026
!!    Andrew Benson <abenson@carnegiescience.edu>
!!
!! This file is part of Galacticus.
!!
!!    Galacticus is free software: you can redistribute it and/or modify
!!    it under the terms of the GNU General Public License as published by
!!    the Free Software Foundation, either version 3 of the License, or
!!    (at your option) any later version.
!!
!!    Galacticus is distributed in the hope that it will be useful,
!!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!    GNU General Public License for more details.
!!
!!    You should have received a copy of the GNU General Public License
!!    along with Galacticus.  If not, see <http://www.gnu.org/licenses/>.

!!{RST
Contains a program to test features of cryptographic hashes.
!!}

program Test_Hashes_Cryptographic
  !!{RST
  Contains a program to test features of cryptographic hashes.
  !!}
  use :: Display             , only : displayVerbositySet, verbosityLevelStandard
  use :: File_Utilities      , only : File_Remove
  use :: Hashes_Cryptographic, only : Hash_MD5           , Hash_SHA256_File
  use :: ISO_Varying_String  , only : assignment(=)      , char                  , varying_string
  use :: Unit_Tests          , only : Assert             , Unit_Tests_Begin_Group, Unit_Tests_End_Group, Unit_Tests_Finish
  implicit none
  type   (varying_string) :: myHash  , myText, &
       &                     fileName
  integer                 :: fileUnit, status

  ! Set verbosity level.
  call displayVerbositySet(verbosityLevelStandard)
  ! Begin unit tests.
  call Unit_Tests_Begin_Group("Cryptographic hashes")
  ! Hash a simple phrase and compare the result with the hash generated by the Linux md5sum command.
  myText="dolphin monkey badger marmoset"
  myHash=Hash_MD5(myText)
  call Assert("MD5 hash [c.f. `md5sum`]",char(myHash),"a2c605b304c5be9b05e0107e8f419200")
  ! Hash the contents of a file. The content used here is the second test case given for SHA-256 by FIPS 180-4, so the expected
  ! hash is that published in the standard (and is also what `sha256sum` reports).
  fileName='sha256TestVector.tmp'
  open(newUnit=fileUnit,file=char(fileName),status='replace',form='unformatted',access='stream')
  write (fileUnit) 'abc'
  close(fileUnit)
  myHash=Hash_SHA256_File(fileName)
  call Assert(                                                                    &
       &      "SHA-256 file hash [c.f. FIPS 180-4, `sha256sum`]"                , &
       &      char(myHash)                                                      , &
       &      "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"  &
       &     )
  call File_Remove(fileName)
  ! An unreadable file must be reported as such, rather than yielding a hash which might be mistaken for a match.
  fileName='thisFileDoesNotExist.tmp'
  myHash=Hash_SHA256_File(fileName,status=status)
  call Assert("SHA-256 of a missing file reports failure",status /= 0,.true.)
  ! End unit tests.
  call Unit_Tests_End_Group()
  call Unit_Tests_Finish   ()

end program Test_Hashes_Cryptographic
