!! Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
!!           2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026
!!    Andrew Benson <abenson@carnegiescience.edu>
!!
!! This file is part of Galacticus.
!!
!!    Galacticus is free software: you can redistribute it and/or modify
!!    it under the terms of the GNU General Public License as published by
!!    the Free Software Foundation, either version 3 of the License, or
!!    (at your option) any later version.
!!
!!    Galacticus is distributed in the hope that it will be useful,
!!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!    GNU General Public License for more details.
!!
!!    You should have received a copy of the GNU General Public License
!!    along with Galacticus.  If not, see <http://www.gnu.org/licenses/>.

!!{RST
Contains a program to test the fitting functions used by the splashback radius classes.
!!}

!+ Implemented by Andrew Benson with assistance from Claude.

program Test_Splashback_Radii
  !!{RST
  Tests the fitting functions used by the splashback radius classes against reference values computed using the `Colossus
  <https://bdiemer.bitbucket.io/colossus/>`_ toolkit. The reference values are tabulated in
  ``testSuite/data/splashbackRadiiColossus/``, and are regenerated by the ``generate.py`` script in that directory.
  !!}
  use :: Display                                    , only : displayVerbositySet, verbosityLevelStandard
  use :: File_Utilities                             , only : Count_Lines_in_File
  use :: Input_Paths                                , only : inputPath          , pathTypeExec
  use :: ISO_Varying_String                         , only : varying_string     , assignment(=)         , operator(//)        , char
  use :: Unit_Tests                                 , only : Assert             , Unit_Tests_Begin_Group, Unit_Tests_End_Group, Unit_Tests_Finish
  use :: Dark_Matter_Halo_Splashback_Radii
  implicit none
  type            (varying_string  )                              :: fileName
  character       (len=1024        )                              :: line
  double precision                  , allocatable, dimension(:  ) :: gamma                                          , peakHeight           , &
       &                                                             omegaMatter                                    , radiusTarget         , &
       &                                                             massTarget                                     , scatterRadiusTarget  , &
       &                                                             scatterMassTarget                              , radius               , &
       &                                                             mass                                           , scatterRadius        , &
       &                                                             scatterMass                                    , accretionRate        , &
       &                                                             densityContrast                                , densityContrastTarget
  integer                           , allocatable, dimension(:  ) :: definition
  type            (diemerParameters)                              :: parametersRadius                               , parametersMass
  type            (diemerScatterParameters)                       :: scatterRadiusParameters                        , scatterMassParameters
  integer                                                         :: dataFile                                       , status               , &
       &                                                             i                                              , countLines           , &
       &                                                             iModel
  double precision                                                :: p
  character       (len=8           ), dimension(2), parameter     :: modelLabel             =['diemer17','diemer20']

  ! Set verbosity level.
  call displayVerbositySet(verbosityLevelStandard)
  call Unit_Tests_Begin_Group("splashback radii")

  ! Test the Diemer et al. (2017) and Diemer (2020) models.
  do iModel=1,2
     fileName  =inputPath(pathTypeExec)//'testSuite/data/splashbackRadiiColossus/'//trim(modelLabel(iModel))//'.txt'
     countLines=Count_Lines_in_File(fileName,comment_char='#')
     allocate(definition         (countLines))
     allocate(gamma              (countLines))
     allocate(peakHeight         (countLines))
     allocate(omegaMatter        (countLines))
     allocate(radiusTarget       (countLines))
     allocate(massTarget         (countLines))
     allocate(scatterRadiusTarget(countLines))
     allocate(scatterMassTarget  (countLines))
     allocate(radius             (countLines))
     allocate(mass               (countLines))
     allocate(scatterRadius      (countLines))
     allocate(scatterMass        (countLines))
     i=0
     open(newUnit=dataFile,file=char(fileName),status='old',form='formatted')
     do while (.true.)
        read (dataFile,'(a)',ioStat=status) line
        if (status /= 0) exit
        if (line(1:1) == "#") cycle
        i=i+1
        read (line,*) definition(i),gamma(i),peakHeight(i),omegaMatter(i),radiusTarget(i),massTarget(i),scatterRadiusTarget(i),scatterMassTarget(i)
     end do
     close(dataFile)
     ! Evaluate the fitting functions.
     do i=1,countLines
        call parametersGet(iModel,definition(i),p,parametersRadius,parametersMass,scatterRadiusParameters,scatterMassParameters)
        radius       (i)=diemerRatio  (parametersRadius       ,p,gamma(i),peakHeight(i),omegaMatter(i))
        mass         (i)=diemerRatio  (parametersMass         ,p,gamma(i),peakHeight(i),omegaMatter(i))
        scatterRadius(i)=diemerScatter(scatterRadiusParameters,p,gamma(i),peakHeight(i)               )
        scatterMass  (i)=diemerScatter(scatterMassParameters  ,p,gamma(i),peakHeight(i)               )
     end do
     call Unit_Tests_Begin_Group(trim(modelLabel(iModel)))
     call Assert('Rₛₚ/R₂₀₀ₘ'   ,radius       ,radiusTarget       ,relTol=1.0d-6)
     call Assert('Mₛₚ/M₂₀₀ₘ'   ,mass         ,massTarget         ,relTol=1.0d-6)
     call Assert('σ(Rₛₚ/R₂₀₀ₘ)',scatterRadius,scatterRadiusTarget,relTol=1.0d-6)
     call Assert('σ(Mₛₚ/M₂₀₀ₘ)',scatterMass  ,scatterMassTarget  ,relTol=1.0d-6)
     call Unit_Tests_End_Group()
     deallocate(definition,gamma,peakHeight,omegaMatter,radiusTarget,massTarget,scatterRadiusTarget,scatterMassTarget)
     deallocate(radius,mass,scatterRadius,scatterMass)
  end do

  ! Test the Shi (2016) model.
  fileName  =inputPath(pathTypeExec)//'testSuite/data/splashbackRadiiColossus/shi2016.txt'
  countLines=Count_Lines_in_File(fileName,comment_char='#')
  allocate(accretionRate        (countLines))
  allocate(omegaMatter          (countLines))
  allocate(radiusTarget         (countLines))
  allocate(densityContrastTarget(countLines))
  allocate(radius               (countLines))
  allocate(densityContrast      (countLines))
  i=0
  open(newUnit=dataFile,file=char(fileName),status='old',form='formatted')
  do while (.true.)
     read (dataFile,'(a)',ioStat=status) line
     if (status /= 0) exit
     if (line(1:1) == "#") cycle
     i=i+1
     read (line,*) accretionRate(i),omegaMatter(i),radiusTarget(i),densityContrastTarget(i)
  end do
  close(dataFile)
  do i=1,countLines
     radius         (i)=shi2016RadiusRatioEvaluate    (accretionRate(i),omegaMatter(i))
     densityContrast(i)=shi2016DensityContrastEvaluate(accretionRate(i),omegaMatter(i))
  end do
  call Unit_Tests_Begin_Group("shi2016")
  call Assert('Rₛₚ/R₂₀₀ₘ',radius         ,radiusTarget         ,relTol=1.0d-6)
  call Assert('Δₛₚ'      ,densityContrast,densityContrastTarget,relTol=1.0d-6)
  call Unit_Tests_End_Group()

  call Unit_Tests_End_Group()
  call Unit_Tests_Finish   ()

contains

  subroutine parametersGet(iModel,iDefinition,p,parametersRadius,parametersMass,scatterRadiusParameters,scatterMassParameters)
    !!{RST
    Return the fitting-function coefficients, and the percentile value :math:`p`, corresponding to the given model and
    splashback definition indices. The definition indices match the order of the ``splashbackDefinition`` enumeration.
    !!}
    use :: Error, only : Error_Report
    implicit none
    integer                                              , intent(in   ) :: iModel                 , iDefinition
    double precision                                     , intent(  out) :: p
    type            (diemerParameters                   ), intent(  out) :: parametersRadius       , parametersMass
    type            (diemerScatterParameters            ), intent(  out) :: scatterRadiusParameters, scatterMassParameters
    type            (enumerationSplashbackDefinitionType)                :: definition_

    select case (iDefinition)
    case (1)
       definition_=splashbackDefinitionMean
    case (2)
       definition_=splashbackDefinitionPercentile50
    case (3)
       definition_=splashbackDefinitionPercentile75
    case (4)
       definition_=splashbackDefinitionPercentile87
    case (5)
       definition_=splashbackDefinitionPercentile90
    case default
       definition_=splashbackDefinitionMean
       call Error_Report('unknown splashback definition index'//{introspection:location})
    end select
    p=diemerPercentileValue(definition_)
    if (iModel == 1) then
       if (definition_ == splashbackDefinitionMean) then
          parametersRadius       =diemer2017ParametersRadiusMean
          parametersMass         =diemer2017ParametersMassMean
          scatterRadiusParameters=diemer2017ScatterRadiusMean
          scatterMassParameters  =diemer2017ScatterMassMean
       else
          parametersRadius       =diemer2017ParametersRadiusPercentile
          parametersMass         =diemer2017ParametersMassPercentile
          scatterRadiusParameters=diemer2017ScatterRadiusPercentile
          scatterMassParameters  =diemer2017ScatterMassPercentile
       end if
    else
       if (definition_ == splashbackDefinitionMean) then
          parametersRadius       =diemer2020ParametersRadiusMean
          parametersMass         =diemer2020ParametersMassMean
          scatterRadiusParameters=diemer2020ScatterRadiusMean
          scatterMassParameters  =diemer2020ScatterMassMean
       else
          parametersRadius       =diemer2020ParametersRadiusPercentile
          parametersMass         =diemer2020ParametersMassPercentile
          scatterRadiusParameters=diemer2020ScatterRadiusPercentile
          scatterMassParameters  =diemer2020ScatterMassPercentile
       end if
    end if
    return
  end subroutine parametersGet

end program Test_Splashback_Radii
