#!/usr/bin/env python3
"""Run halo mass function validation models and extract likelihoods.

Runs the halo mass function validation models for a given validation group
(see `testSuite/parameters/validation/haloMassFunction/manifest.json` - groups
are generated by `constraints/pipelines/darkMatter/haloMassFunctionValidationGenerate.py`),
evaluates the likelihood of each model with respect to the corresponding
N-body halo mass function data (replicating the likelihood used in calibrating
the halo mass function model of Benson et al. 2026;
https://ui.adsabs.harvard.edu/abs/2026arXiv260612137B), and writes benchmark
and plot data files for the validation web pages.

Usage:  validate-haloMassFunction.py <group> [workers]

where <group> is one of the group names in the manifest (e.g. "MDPL",
"SymphonyMilkyWayZ0", "COZMIC"), and [workers] optionally sets the number of
models to run concurrently (defaulting to the number of available CPUs).

Models within a group that differ only in their realization (e.g. the
different halos of the Symphony Milky Way suite) are stacked into a single
analysis: their likelihoods are summed, and their mass functions are combined.
For the "SymphonyMilkyWayZ0" group an additional analysis of the environmental
dependence of the halo mass function is performed, comparing the ratio of
measured to expected halo counts in each realization as a function of the
environmental overdensity of that realization.
"""

import concurrent.futures
import json
import os
import re
import subprocess
import sys

import numpy as np

import validate
import validateHaloMassFunction

pathParameters = "parameters/validation/haloMassFunction/"
pathOutputs    = "outputs/validation/haloMassFunction/"

# Parse arguments.
if len(sys.argv) < 2 or len(sys.argv) > 3:
    print("Usage: validate-haloMassFunction.py <group> [workers]")
    sys.exit(1)
group   = sys.argv[1]
workers = int(sys.argv[2]) if len(sys.argv) == 3 else None
if workers is None:
    workers = len(os.sched_getaffinity(0)) if hasattr(os, "sched_getaffinity") else os.cpu_count()

# Read the manifest, and find the cases for this group.
with open(pathParameters+"manifest.json") as file:
    manifest = json.load(file)
if group not in manifest["groups"]:
    print(f"FAIL: unknown validation group '{group}' - known groups: {', '.join(manifest['groups'])}")
    sys.exit(1)
cases                              = manifest["groups"][group]["cases"]
varianceFractionalModelDiscrepancy = manifest["varianceFractionalModelDiscrepancy"]
pathDataStatic                     = os.environ["GALACTICUS_DATA_PATH"]+"/static"

# Create output paths.
os.makedirs("outputs/validation/haloMassFunction", exist_ok=True)

# Run all models in the group.
def run(case):
    status = subprocess.run(
        "cd ..; ./Galacticus.exe testSuite/"+pathParameters+"'"+case["parameterFile"]+"'",
        shell=True, capture_output=True, text=True,
        env=dict(os.environ, OMP_NUM_THREADS="1"),
    )
    return case, status

failed = False
with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
    for case, status in executor.map(run, cases):
        if status.returncode == 0:
            print(  "SUCCESS: model '"+case["parameterFile"]+"'")
        else:
            print(     "FAIL: model '"+case["parameterFile"]+"'")
            print(status.stdout[-2000:])
            print(status.stderr[-2000:])
            failed = True
if failed:
    sys.exit(1)

# Evaluate likelihoods, and aggregate cases which differ only in their
# realization (e.g. different halos of the same suite).
aggregates = {}
for case in cases:
    match = re.match(
        r"^haloMassFunctionBase_([^_]+)_([^_]+)_([^_]+)_([^_]+)_([^_]+)_z(\d+\.\d+)\.xml$",
        case["parameterFile"],
    )
    if match is None:
        print("FAIL: unable to parse parameter file name '"+case["parameterFile"]+"'")
        sys.exit(1)
    suite, groupName, resolution, simulation, realization, redshift = match.groups()
    model = validateHaloMassFunction.readModel(
        pathOutputs+re.sub(r"^haloMassFunctionBase_(.+)\.xml$", r"haloMassFunction_\g<1>.hdf5", case["parameterFile"])
    )
    data  = validateHaloMassFunction.readData(case["targetData"].replace("%DATASTATICPATH%", pathDataStatic))
    negativeLogLikelihood, bins = validateHaloMassFunction.negativeLogLikelihood(
        model, data,
        case["massRangeMinimum"], case.get("massRangeMaximum"),
        varianceFractionalModelDiscrepancy,
    )
    key = (suite, groupName, resolution, simulation, redshift)
    aggregates.setdefault(key, []).append(
        {
            "case"                 : case,
            "realization"          : realization,
            "negativeLogLikelihood": negativeLogLikelihood,
            "bins"                 : bins,
            "model"                : model,
            "data"                 : data,
        }
    )

# Reference grid used to align mass bins when stacking realizations.
massReference       = 1.0e0
intervalLogarithmic = np.log(10.0)/10.0

likelihoods = []
results     = []
for key in sorted(aggregates.keys()):
    suite, groupName, resolution, simulation, redshift = key
    members = aggregates[key]
    name    = f"{suite} {groupName} {simulation} {resolution} z={redshift}"
    if len(members) > 1:
        name += f" ({len(members)} realizations)"
    # Sum likelihoods over realizations.
    negativeLogLikelihood = sum(member["negativeLogLikelihood"] for member in members)
    print(name+"\t"+str(negativeLogLikelihood))
    likelihoods.append(
        {
            "name" : "Halo mass function - Likelihood - "+name,
            "unit" : "-logℒ"                                   ,
            "value": str(np.abs(negativeLogLikelihood))
        }
    )
    # Stack mass functions over realizations on a common mass grid.
    indices = {}
    for member in members:
        binIndices = np.rint(np.log(member["bins"]["mass"]/massReference)/intervalLogarithmic).astype(int)
        for i, binIndex in enumerate(binIndices):
            entry = indices.setdefault(
                binIndex,
                {"mass": member["bins"]["mass"][i], "count": 0.0, "countMean": 0.0, "variance": 0.0, "conversion": 0.0},
            )
            conversion           = member["bins"]["countMean"][i]/member["bins"]["massFunctionModel"][i]
            entry["count"      ] += member["bins"]["count"    ][i]
            entry["countMean"  ] += member["bins"]["countMean"][i]
            entry["variance"   ] += member["bins"]["countMean"][i]+varianceFractionalModelDiscrepancy*member["bins"]["countMean"][i]**2
            entry["conversion" ] += conversion
    massStacked              = np.array([indices[i]["mass"                          ] for i in sorted(indices)])
    massFunctionModelStacked = np.array([indices[i]["countMean"]/indices[i]["conversion"] for i in sorted(indices)])
    massFunctionDataStacked  = np.array([indices[i]["count"    ]/indices[i]["conversion"] for i in sorted(indices)])
    massFunctionErrorStacked = np.array([np.sqrt(indices[i]["variance"])/indices[i]["conversion"] for i in sorted(indices)])
    results.append(
        {
            "attributes": {
                "name"         : name,
                "logLikelihood": str(-negativeLogLikelihood),
                "xAxisLabel"   : "Mₕₐₗₒ [M☉]",
                "yAxisLabel"   : "dn/dlnM [Mpc⁻³]",
                "xAxisIsLog"   : "1",
                "yAxisIsLog"   : "1",
                "targetLabel"  : f"{suite} {groupName} simulation",
            },
            "data": {
                "xDataset"      : list(massStacked             ),
                "yDataset"      : list(massFunctionModelStacked),
                "yError"        : list(massFunctionErrorStacked),
                "yDatasetTarget": list(massFunctionDataStacked ),
            },
        }
    )
validate.write(likelihoods, results, "haloMassFunction"+group, "testSuite/"+pathParameters)

# For the Milky Way z=0 group, additionally analyze the environmental
# dependence of the halo mass function using the resolutionX1 realizations.
# Halos are counted in the mass range (4-40)x10^8 Msun (as in Benson et al.
# 2026), and both the measured and expected counts (converted to number
# densities) are normalized by the mean, over realizations, of the expected
# number density - the environmental dependence then appears as a trend of
# both model and data with the environmental overdensity of the realizations.
if group == "SymphonyMilkyWayZ0":
    massWindowMinimum = 4.0e8
    massWindowMaximum = 4.0e9
    members = []
    for key in aggregates:
        suite, groupName, resolution, simulation, redshift = key
        if resolution == "resolutionX1":
            members.extend(aggregates[key])
    negativeLogLikelihood = 0.0
    overdensities         = []
    densitiesModel        = []
    densitiesData         = []
    densitiesError        = []
    for member in members:
        negativeLogLikelihoodWindow, binsWindow = validateHaloMassFunction.negativeLogLikelihood(
            member["model"], member["data"],
            massWindowMinimum, massWindowMaximum,
            varianceFractionalModelDiscrepancy,
        )
        negativeLogLikelihood += negativeLogLikelihoodWindow
        conversion             = binsWindow["countMean"][0]/binsWindow["massFunctionModel"][0]
        variance               = binsWindow["countMean"]+varianceFractionalModelDiscrepancy*binsWindow["countMean"]**2
        overdensities .append(member["data"]["overdensityEnvironment"])
        densitiesModel.append(np.sum (       binsWindow["countMean"])/conversion)
        densitiesData .append(np.sum (       binsWindow["count"    ])/conversion)
        densitiesError.append(np.sqrt(np.sum(variance               ))/conversion)
    overdensities  = np.array(overdensities )
    densitiesModel = np.array(densitiesModel)
    densitiesData  = np.array(densitiesData )
    densitiesError = np.array(densitiesError)
    normalization  = np.mean(densitiesModel)
    order          = np.argsort(overdensities)
    name           = f"Symphony MilkyWay CDM resolutionX1 z={redshift} environments"
    print(name+"\t"+str(negativeLogLikelihood))
    likelihoods = [
        {
            "name" : "Halo mass function - Likelihood - "+name,
            "unit" : "-logℒ"                                   ,
            "value": str(np.abs(negativeLogLikelihood))
        }
    ]
    results     = [
        {
            "attributes": {
                "name"         : name+" (4×10⁸ ≤ M/M☉ ≤ 4×10⁹)",
                "logLikelihood": str(-negativeLogLikelihood),
                "xAxisLabel"   : "environmental overdensity δ",
                "yAxisLabel"   : "n/⟨nₘₒdₑₗ⟩",
                "xAxisIsLog"   : "0",
                "yAxisIsLog"   : "0",
                "targetLabel"  : "Symphony MilkyWay simulations",
            },
            "data": {
                "xDataset"      : list(overdensities [order]              ),
                "yDataset"      : list(densitiesModel[order]/normalization),
                "yError"        : list(densitiesError[order]/normalization),
                "yDatasetTarget": list(densitiesData [order]/normalization),
            },
        }
    ]
    validate.write(likelihoods, results, "haloMassFunctionSymphonyMilkyWayEnvironments", "testSuite/"+pathParameters)

print("SUCCESS: halo mass function validation group '"+group+"'")
