*** Makefile.orig	2011-04-16 09:11:04.497172845 -0700
--- Makefile	2011-04-16 09:22:16.099172846 -0700
***************
*** 55,61 ****
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
  ssp_gen.o getmags.o gasdev.o spline.o splint.o ran.o ran_state.o \
! locate.o qromb.o polint.o trapzd.o tridag.o sps_setup.o	ran2.o	 \
  pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o velbroad.o mod_agb.o \
  write_isochrone.o sfhstat.o
--- 55,61 ----
  
  COMMON = sps_vars.o nrtype.o sps_utils.o nr.o nrutil.o compsp.o	 \
  ssp_gen.o getmags.o gasdev.o spline.o splint.o ran.o ran_state.o \
! locate.o qromb.o polint.o galacticus_IMF.o trapzd.o tridag.o sps_setup.o	ran2.o	 \
  pz_convol.o get_tuniv.o imf.o imf_weight.o add_dust.o getspec.o \
  add_bs.o mod_hb.o add_remnants.o getindx.o velbroad.o mod_agb.o \
  write_isochrone.o sfhstat.o
