# Provides functions used for validation of models.
# Andrew Benson (12-August-2024)
"""Functions for validating Galacticus model output against observational constraints.

This module provides utilities to extract likelihood measures from model HDF5
output files and compare them against stored reference values, supporting
automated regression testing and model validation workflows.
"""
import os
import numpy as np
import h5py
import re
import json
import codecs
from git import Repo

def extract(fileName, name, suffix, parameterFileName):
    """Extract likelihood measures and result data from a Galacticus model output file.

    Reads an HDF5 output file produced by Galacticus and, for each analysis
    group, computes the negative log-likelihood ``-log ℒ`` and collects
    associated x/y data arrays for comparison plots.

    The likelihood measure is defined as the *unnormalized* negative log-
    likelihood.  For a normal distribution this corresponds to

    .. code-block:: text

        -log ℒ = Σᵢ ½(x - xᵢ)² / σᵢ²

    Using the unnormalized form means that a fractional shift ``Δf`` of the
    model relative to the data produces the same fractional shift in the
    metric:

    .. code-block:: text

        Δ(-log ℒ) / (-log ℒ) = 2 Δf

    This makes it safe to use a percentage-change threshold even when the
    absolute likelihood is low.

    Parameters
    ----------
    fileName : str
        Path to the HDF5 output file generated by Galacticus.
    name : str
        Human-readable label for this model run, used to prefix likelihood
        entry names in the returned list.
    suffix : str
        File-name suffix appended when writing result JSON files.
    parameterFileName : str
        Path to the Galacticus parameter XML file used to produce *fileName*.
        Stored in the result metadata for traceability.

    Returns
    -------
    tuple[list[dict], list[dict]]
        A 2-tuple ``(likelihoods, results)`` where:

        *likelihoods* is a list of dicts, one per analysis, each with keys
        ``"name"``, ``"unit"`` (always ``"-logℒ"``), and ``"value"`` (the
        string representation of ``|-log ℒ|``).

        *results* is a list of dicts containing plot-ready x/y data, error
        estimates, and metadata for each analysis that defines a supported
        ``type`` attribute.
    """
    likelihoods = []
    results     = []
    model       = h5py.File(fileName,"r")
    analyses    = model['analyses']
    for analysisName, analysisGroup in analyses.items():
        attributes = {
            "name"       : analysisName,
            "xAxisLabel" : "x",
            "yAxisLabel" : "y",
            "xAxisIsLog" :  0 ,
            "yAxisIsLog" :  1 ,
            "targetLabel": "data"
        }
        for attributeName in analysisGroup.attrs:
            attributes[attributeName] = analysisGroup.attrs[attributeName]
            if isinstance(attributes[attributeName], bytes):
                attributes[attributeName] = attributes[attributeName].decode('utf-8')
        logLikelihood = attributes['logLikelihood']
        print(analysisName+"\t"+str(logLikelihood))
        likelihoods.append(
            {
        	"name" : name+" - Likelihood - "+analysisName,
        	"unit" : "-logℒ"                            ,
        	"value": str(np.abs(logLikelihood))
            }
            )
        # Skip cases for which we have no "type" specified.
        if not "type" in attributes:
            print("Warning: analysis '"+analysisName+"' has no 'type' attribute, so it can not be processed.")
        elif attributes['type'] == "function1D":
            # Simple 1D function - will be shown as an x-y scatter plot.
            # Validate attributes.
            datasetNames = (
        	{"name": 'xDataset'         , "required": 1},
        	{"name": 'yDataset'         , "required": 1},
        	{"name": 'yDatasetTarget'   , "required": 0},
        	{"name": 'yCovariance'      , "required": 0},
        	{"name": 'yCovarianceTarget', "required": 0},
        	{"name": 'yErrorLower'      , "required": 0},
        	{"name": 'yErrorUpper'      , "required": 0},
        	{"name": 'yErrorLowerTarget', "required": 0},
        	{"name": 'yErrorUpperTarget', "required": 0},
            )
            for dataset in datasetNames:
                if dataset['required'] and not dataset['name'] in attributes:
                    print("Error: attribute '"+dataset['name']+"' is missing from analysis '"+analysisName+"' but is required.")
                    os.abort()
            # Read the datasets.
            data = {}
            for dataset in datasetNames:
                if dataset['name'] in attributes:
                    analysisDatasetName = attributes[dataset['name']]
                    if not analysisDatasetName in analysisGroup.keys():
                        print("Analysis: '"    +analysisName       +"'")
                        print("Generic name: '"+dataset['name']    +"'")
                        print("Actual name: '" +analysisDatasetName+"'")
                        print("Available datasets:")
                        print("\n".join(analysisGroup.keys()))
                        print("failed to find dataset")
                        os.abort()
                    data[dataset['name']] = analysisGroup[analysisDatasetName][:]
            # Extract errors.
            if "yCovariance" in data:
                data['yError'      ] = np.sqrt(np.diagonal(data['yCovariance'      ]))
                del data['yCovariance'      ]
            if "yCovarianceTarget" in data:
                data['yErrorTarget'] = np.sqrt(np.diagonal(data['yCovarianceTarget']))
                del data['yCovarianceTarget']
            # Store results.
            result = {
                "attributes": {},
                "data"      : {}
            }
            for attributeName in attributes:
                if re.search(r"^[xy]AxisIsLog$",attributeName) or attributeName == "logLikelihood":
                    result['attributes'][attributeName] = str(attributes[attributeName])
                else:
                    # LaTeX conversions.
                    attributes[attributeName] = re.sub(r"\$",""                        ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\mathrm\{([^\}]+)\}",r"\g<1>",attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\hbox\{([^\}]+)\}",r"\g<1>"  ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\odot","☉"                   ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\langle","⟨"                 ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\rangle","⟩"                 ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\star","★"                   ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\log_\{10\}","log₁₀"         ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\sigma","σ"                  ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\^\{-1\}","⁻¹"                ,attributes[attributeName])
                    attributes[attributeName] = re.sub(r"\\,"," "                      ,attributes[attributeName])
                    result['attributes'][attributeName] = attributes[attributeName]
            for dataName in data:
                result['data'][dataName] = list(data[dataName])
            results.append(result)
        else:
            print(f"Warning: analysis '{analysisName}' has unknown 'type' attribute '{attributes['type']}', so it can not be processed.")
    # Write benchmark results.
    f = codecs.open("outputs/validate_"+suffix+".json", "w", "utf-8")
    f.write(json.dumps(likelihoods,indent=4,ensure_ascii=False))
    f.close()
    # Interface with git.
    repo         = Repo(os.environ['GALACTICUS_EXEC_PATH'])
    actor        = repo.head.commit.author
    lastRevision = repo.head.object.hexsha
    authorName   = actor.name
    authorEmail  = actor.email
    authorDate   = str(repo.head.commit.committed_datetime)
    message      = repo.head.commit.message
    # Write results.
    output = {
        "repoUrl"      : "https://github.com/galacticusorg/galacticus",
        "parameterFile": parameterFileName,
        "commit"       : {
            "author":  {
                "name" : authorName,
                "email": authorEmail
            },
            "id"       : lastRevision,
            "message"  : message,
            "timestamp": authorDate,
            "url"      : "https://github.com/galacticusorg/galacticus/commit/"+lastRevision
        },
        "results": results
    }
    f = codecs.open("outputs/results_"+suffix+".json", "w", "utf-8")
    f.write("window.ANALYSES_DATA = ")
    f.write(json.dumps(output,indent=4,ensure_ascii=False))
    f.close()
