!! Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
!!           2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026
!!    Andrew Benson <abenson@carnegiescience.edu>
!!
!! This file is part of Galacticus.
!!
!!    Galacticus is free software: you can redistribute it and/or modify
!!    it under the terms of the GNU General Public License as published by
!!    the Free Software Foundation, either version 3 of the License, or
!!    (at your option) any later version.
!!
!!    Galacticus is distributed in the hope that it will be useful,
!!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!    GNU General Public License for more details.
!!
!!    You should have received a copy of the GNU General Public License
!!    along with Galacticus.  If not, see <http://www.gnu.org/licenses/>.

!+    Contributions to this file made by: Andrew Benson, Claude.

  !!{RST
  Implements a task which generates a design (a set of points in parameter space) for training an emulator.
  !!}

  use :: Model_Parameters                , only : modelParameterList
  use :: Posterior_Sampling_State_Samples, only : posteriorSamplesClass

  !![
  <task name="taskEmulatorDesign" docformat="rst">
   <description>
   A task which generates a design---a set of points in the space of model parameters at which a model is to be run---for
   training an emulator (see :ref:`manual-sec-Emulation`). The parameters to vary, and their priors and mappings, are given by
   ``[modelParameter]`` blocks exactly as for posterior sampling, and the points are generated by the ``[posteriorSamples]``
   object (typically :galacticus-class:`posteriorSamplesSobol`), in the space of prior quantiles.

   The design is written to the HDF5 file ``[designFileName]``, containing the parameter names, the prior quantiles and
   values of each parameter at each point, and a description of each prior and mapping (see
   :ref:`manual-sec-EmulatorFileFormat`). For each run of the model a Galacticus change file,
   ``[changeFilesRoot]NNNN.xml``, is written which sets each parameter to its value at the design point, and sets
   ``outputFileName`` to ``[outputFileNameRoot]NNNN.hdf5``. Applying a change file to a base parameter file (e.g.
   ``Galacticus.exe base.xml changes/point0012.xml``) then runs the model at that point.

   If ``[seedPerPoint]`` is ``true`` each run is also given its own random number seed, ``[seedBase]`` plus the (zero-based)
   index of the run, by setting ``randomNumberGenerator/seed``, so that each run uses an independent realization of its merger
   trees; the base parameter file must then specify a ``randomNumberGenerator``. Otherwise all runs share the seed of the base
   parameter file. If ``[realizationsPerPoint]`` is greater than one, each design point is run that many times (requiring
   ``[seedPerPoint]``), and the change files are labeled ``NNNN_R`` for (zero-based) realization ``R``.

   Parameter names may select among multiple copies of a parameter with ``[N]`` or ``[@value='...']``, as in change files, but
   may not select an element of a multi-valued parameter with ``{N}``, which change files can not express.
   </description>
   <descriptorSpecial>descriptorSpecial</descriptorSpecial>
  </task>
  !!]
  type, extends(taskClass) :: taskEmulatorDesign
     !!{RST
     Implementation of a task which generates a design for training an emulator.
     !!}
     private
     type   (modelParameterList   ), allocatable, dimension(:) :: modelParameters_
     class  (posteriorSamplesClass), pointer                   :: posteriorSamples_  => null()
     type   (varying_string       )                            :: designFileName              , changeFilesRoot     , &
          &                                                       outputFileNameRoot
     type   (varying_string       ), allocatable, dimension(:) :: priorClasses                , priorDescriptors    , &
          &                                                       mappers
     logical                                                   :: seedPerPoint
     integer                                                   :: seedBase                    , realizationsPerPoint
   contains
     !![
     <methods docformat="rst">
       <method method="descriptorSpecial" description="Add the model parameters to the descriptor."/>
     </methods>
     !!]
     final     ::                       emulatorDesignDestructor
     procedure :: perform            => emulatorDesignPerform
     procedure :: requiresOutputFile => emulatorDesignRequiresOutputFile
     procedure :: descriptorSpecial  => emulatorDesignDescriptorSpecial
  end type taskEmulatorDesign

  interface taskEmulatorDesign
     !!{RST
     Constructors for the :galacticus-class:`taskEmulatorDesign` task.
     !!}
     module procedure emulatorDesignConstructorParameters
     module procedure emulatorDesignConstructorInternal
  end interface taskEmulatorDesign

contains

  function emulatorDesignConstructorParameters(parameters) result(self)
    !!{RST
    Constructor for the :galacticus-class:`taskEmulatorDesign` task class which takes a parameter set as input.
    !!}
    use :: Error           , only : Error_Report
    use :: Input_Parameters, only : inputParameter      , inputParameters
    use :: Model_Parameters, only : modelParameterActive, modelParameterClass
    implicit none
    type   (taskEmulatorDesign   )                              :: self
    type   (inputParameters      ), intent(inout)               :: parameters
    type   (modelParameterList   ), allocatable  , dimension(:) :: modelParameters_
    class  (modelParameterClass  ), pointer                     :: modelParameter_
    class  (posteriorSamplesClass), pointer                     :: posteriorSamples_
    type   (varying_string       )                              :: designFileName   , changeFilesRoot, &
         &                                                         outputFileNameRoot
    type   (varying_string       ), allocatable  , dimension(:) :: priorClasses     , priorDescriptors, &
         &                                                         mappers
    logical                                                     :: seedPerPoint
    integer                                                     :: seedBase         , realizationsPerPoint, &
         &                                                         i

    !![
    <inputParameter docformat="rst">
      <name>designFileName</name>
      <defaultValue>var_str('design.hdf5')</defaultValue>
      <description>
      The name of the HDF5 file to which the design is written.
      </description>
      <source>parameters</source>
    </inputParameter>
    <inputParameter docformat="rst">
      <name>changeFilesRoot</name>
      <defaultValue>var_str('changes/point')</defaultValue>
      <description>
      The root of the names of the change files written for each run; the run label and ``.xml`` are appended.
      </description>
      <source>parameters</source>
    </inputParameter>
    <inputParameter docformat="rst">
      <name>outputFileNameRoot</name>
      <defaultValue>var_str('models/point')</defaultValue>
      <description>
      The root of the output file name set for each run; the run label and ``.hdf5`` are appended.
      </description>
      <source>parameters</source>
    </inputParameter>
    <inputParameter docformat="rst">
      <name>seedPerPoint</name>
      <defaultValue>.false.</defaultValue>
      <description>
      If true, give each run its own random number seed (and so an independent realization of its merger trees). Otherwise all
      runs share the seed of the base parameter file.
      </description>
      <source>parameters</source>
    </inputParameter>
    <inputParameter docformat="rst">
      <name>seedBase</name>
      <defaultValue>1</defaultValue>
      <description>
      If ``[seedPerPoint]`` is true, the seed of each run is this value plus the (zero-based) index of the run.
      </description>
      <source>parameters</source>
      <minimum>0</minimum>
    </inputParameter>
    <inputParameter docformat="rst">
      <name>realizationsPerPoint</name>
      <defaultValue>1</defaultValue>
      <description>
      The number of runs, with different random number seeds, to make at each design point.
      </description>
      <source>parameters</source>
      <minimum>1</minimum>
    </inputParameter>
    <objectBuilder class="posteriorSamples" name="posteriorSamples_" source="parameters"/>
    !!]
    ! Build the list of model parameters.
    allocate(modelParameters_(parameters%copiesCount("modelParameter",zeroIfNotPresent=.true.)))
    if (size(modelParameters_) < 1) call Error_Report('at least one active `modelParameter` must be given'//{introspection:location})
    call emulatorDesignPriorsRecord(parameters,priorClasses,priorDescriptors,mappers)
    do i=1,size(modelParameters_)
       !![
       <objectBuilder class="modelParameter" name="modelParameter_" source="parameters" copy="i" />
       !!]
       select type (modelParameter_)
       class is (modelParameterActive)
          modelParameters_(i)%modelParameter_ => modelParameter_
          !![
          <referenceCountIncrement owner="modelParameters_(i)" object="modelParameter_"/>
          !!]
       class default
          call Error_Report('only active model parameters may be varied in a design'//{introspection:location})
       end select
       !![
       <objectDestructor name="modelParameter_"/>
       !!]
    end do
    self=taskEmulatorDesign(modelParameters_,posteriorSamples_,designFileName,changeFilesRoot,outputFileNameRoot,seedPerPoint,seedBase,realizationsPerPoint,priorClasses,priorDescriptors,mappers)
    !![
    <inputParametersValidate source="parameters" multiParameters="modelParameter"/>
    <objectDestructor name="posteriorSamples_"/>
    !!]
    do i=1,size(modelParameters_)
       !![
       <objectDestructor name="modelParameters_(i)%modelParameter_"/>
       !!]
    end do
    return
  end function emulatorDesignConstructorParameters

  function emulatorDesignConstructorInternal(modelParameters_,posteriorSamples_,designFileName,changeFilesRoot,outputFileNameRoot,seedPerPoint,seedBase,realizationsPerPoint,priorClasses,priorDescriptors,mappers) result(self)
    !!{RST
    Internal constructor for the :galacticus-class:`taskEmulatorDesign` task class. The prior classes, prior descriptors (the
    serialized prior parameters), and mapper classes are recorded in the design file. If not supplied they are recorded as
    ``unknown``.
    !!}
    use :: Error             , only : Error_Report
    use :: ISO_Varying_String, only : var_str
    implicit none
    type   (taskEmulatorDesign   )                              :: self
    type   (modelParameterList   ), intent(in   ), dimension(:) :: modelParameters_
    class  (posteriorSamplesClass), intent(in   ), target       :: posteriorSamples_
    type   (varying_string       ), intent(in   )               :: designFileName   , changeFilesRoot     , &
         &                                                         outputFileNameRoot
    logical                       , intent(in   )               :: seedPerPoint
    integer                       , intent(in   )               :: seedBase         , realizationsPerPoint
    type   (varying_string       ), intent(in   ), dimension(:), optional :: priorClasses     , priorDescriptors    , &
         &                                                                   mappers
    integer                                                     :: i
    !![
    <constructorAssign variables="*posteriorSamples_, designFileName, changeFilesRoot, outputFileNameRoot, seedPerPoint, seedBase, realizationsPerPoint"/>
    !!]

    if (realizationsPerPoint > 1 .and. .not.seedPerPoint) call Error_Report('`realizationsPerPoint` greater than one requires `seedPerPoint`'//{introspection:location})
    ! Store the model parameters, checking that each can be expressed as a change file path.
    allocate(self%modelParameters_(size(modelParameters_)))
    do i=1,size(modelParameters_)
       if (index(modelParameters_(i)%modelParameter_%name(),'{') > 0)                                                        &
            & call Error_Report(                                                                                           &
            &                   "parameter '"//modelParameters_(i)%modelParameter_%name()//"' selects an element of a "     // &
            &                   "multi-valued parameter (`{N}`), which can not be expressed in a change file"               // &
            &                   {introspection:location}                                                                    &
            &                  )
       self%modelParameters_(i)=modelParameters_(i)
    end do
    allocate(self%priorClasses    (size(modelParameters_)))
    allocate(self%priorDescriptors(size(modelParameters_)))
    allocate(self%mappers         (size(modelParameters_)))
    self%priorClasses    =var_str('unknown')
    self%priorDescriptors=var_str('unknown')
    self%mappers         =var_str('unknown')
    if (present(priorClasses    )) self%priorClasses    =priorClasses
    if (present(priorDescriptors)) self%priorDescriptors=priorDescriptors
    if (present(mappers         )) self%mappers         =mappers
    return
  end function emulatorDesignConstructorInternal

  subroutine emulatorDesignPriorsRecord(parameters,priorClasses,priorDescriptors,mappers)
    !!{RST
    Record the class and (serialized) parameters of the prior, and the class of the mapping, of each ``modelParameter``,
    exactly as given in the parameter file.
    !!}
    use :: Input_Parameters, only : inputParameters
    implicit none
    type   (inputParameters), intent(inout)                            :: parameters
    type   (varying_string ), intent(  out), allocatable, dimension(:) :: priorClasses   , priorDescriptors, &
         &                                                                mappers
    type   (inputParameters)                                           :: parametersModel, parametersPrior
    integer                                                            :: i              , countParameters

    countParameters=parameters%copiesCount('modelParameter',zeroIfNotPresent=.true.)
    allocate(priorClasses    (countParameters))
    allocate(priorDescriptors(countParameters))
    allocate(mappers         (countParameters))
    do i=1,countParameters
       parametersModel    =parameters     %subParameters('modelParameter'             ,copyInstance=i)
       parametersPrior    =parametersModel%subParameters('distributionFunction1DPrior'               )
       call parametersModel%value('distributionFunction1DPrior',priorClasses(i))
       call parametersModel%value('operatorUnaryMapper'        ,mappers     (i))
       priorDescriptors(i)=parametersPrior%serializeToString()
    end do
    return
  end subroutine emulatorDesignPriorsRecord

  subroutine emulatorDesignDestructor(self)
    !!{RST
    Destructor for the :galacticus-class:`taskEmulatorDesign` task class.
    !!}
    implicit none
    type(taskEmulatorDesign), intent(inout) :: self

    !![
    <objectDestructor name="self%posteriorSamples_"/>
    !!]
    return
  end subroutine emulatorDesignDestructor

  subroutine emulatorDesignDescriptorSpecial(self,descriptor)
    !!{RST
    Add the model parameters to the descriptor.
    !!}
    use :: Input_Parameters, only : inputParameters
    implicit none
    class  (taskEmulatorDesign), intent(inout) :: self
    type   (inputParameters   ), intent(inout) :: descriptor
    integer                                    :: i

    if (allocated(self%modelParameters_)) then
       do i=1,size(self%modelParameters_)
          call self%modelParameters_(i)%modelParameter_%descriptor(descriptor)
       end do
    end if
    return
  end subroutine emulatorDesignDescriptorSpecial

  logical function emulatorDesignRequiresOutputFile(self)
    !!{RST
    Specifies that this task does not require the main output file.
    !!}
    implicit none
    class(taskEmulatorDesign), intent(inout) :: self
    !$GLC attributes unused :: self

    emulatorDesignRequiresOutputFile=.false.
    return
  end function emulatorDesignRequiresOutputFile

  subroutine emulatorDesignPerform(self,status)
    !!{RST
    Generate the design, and write the design file and change files.
    !!}
    use            :: Dates_and_Times         , only : Formatted_Date_and_Time
    use            :: Display                 , only : displayIndent             , displayMessage , displayUnindent
    use            :: Error                   , only : Error_Report              , errorStatusSuccess
    use            :: File_Utilities          , only : Directory_Make            , File_Path
    use            :: HDF5_Access             , only : hdf5Access
    use            :: IO_HDF5                 , only : hdf5File                  , hdf5Group
    use            :: ISO_Varying_String      , only : var_str                   , char           , operator(//), operator(/=), &
         &                                             assignment(=)
    use            :: MPI_Utilities           , only : mpiSelf
    use            :: Posterior_Sampling_State, only : posteriorSampleStateSimple
    use            :: String_Handling         , only : operator(//)
    implicit none
    class           (taskEmulatorDesign        ), intent(inout), target                   :: self
    integer                                     , intent(  out), optional                 :: status
    type            (posteriorSampleStateSimple)               , allocatable, dimension(:  ) :: simulationStates
    double precision                                           , allocatable, dimension(:,:) :: values               , quantiles
    type            (varying_string            )               , allocatable, dimension(:  ) :: names                , changeFileNames, &
         &                                                                                      outputFileNames
    integer                                                    , allocatable, dimension(:  ) :: pointIndices         , realizationIndices, &
         &                                                                                      seeds
    type            (varying_string            )                                          :: label                , message
    character       (len=32                    )                                          :: labelFormat          , labelText      , &
         &                                                                                      valueText
    integer                                                                               :: countParameters      , countPoints    , &
         &                                                                                      countRuns            , widthLabel     , &
         &                                                                                      i                    , j              , &
         &                                                                                      iRun                 , iRealization   , &
         &                                                                                      unit

    call displayIndent('Begin task: emulator design')
    ! Generate the design.
    call self%posteriorSamples_%samples(simulationStates,self%modelParameters_)
    countParameters=size(self%modelParameters_)
    countPoints    =size(simulationStates     )
    countRuns      =countPoints*self%realizationsPerPoint
    ! Recover the physical values and prior quantiles of each parameter at each point.
    allocate(values   (countParameters,countPoints))
    allocate(quantiles(countParameters,countPoints))
    do i=1,countPoints
       values(:,i)=simulationStates(i)%get()
       do j=1,countParameters
          values   (j,i)=self%modelParameters_(j)%modelParameter_%unmap          (values(j,i))
          quantiles(j,i)=self%modelParameters_(j)%modelParameter_%priorCumulative(values(j,i))
       end do
    end do
    ! Get the name of each parameter.
    allocate(names(countParameters))
    do j=1,countParameters
       names(j)=self%modelParameters_(j)%modelParameter_%name()
    end do
    ! Construct the list of runs.
    widthLabel=max(4,int(log10(dble(max(countPoints-1,1))))+1)
    write (labelFormat,'(a,i0,a,i0,a)') '(i',widthLabel,'.',widthLabel,')'
    allocate(changeFileNames   (countRuns))
    allocate(outputFileNames   (countRuns))
    allocate(pointIndices      (countRuns))
    allocate(realizationIndices(countRuns))
    allocate(seeds             (countRuns))
    iRun=0
    do i=1,countPoints
       do iRealization=1,self%realizationsPerPoint
          iRun=iRun+1
          write (labelText,labelFormat) i-1
          label=trim(labelText)
          if (self%realizationsPerPoint > 1) label=label//'_'//(iRealization-1)
          changeFileNames   (iRun)=self%changeFilesRoot   //label//'.xml'
          outputFileNames   (iRun)=self%outputFileNameRoot//label//'.hdf5'
          pointIndices      (iRun)=i-1
          realizationIndices(iRun)=iRealization-1
          if (self%seedPerPoint) then
             seeds(iRun)=self%seedBase+iRun-1
          else
             seeds(iRun)=-1
          end if
       end do
    end do
    ! Only the master process writes files.
    if (mpiSelf%isMaster()) then
       ! Write the design file.
       if (File_Path(self%designFileName) /= '') call Directory_Make(File_Path(self%designFileName))
       !$ call hdf5Access%set()
       block
         type(hdf5File ) :: file
         type(hdf5Group) :: group, priorsGroup, runsGroup
         file=hdf5File(self%designFileName,overWrite=.true.,readOnly=.false.)
         call file %writeAttribute('galacticusDesign'                             ,'format'              )
         call file %writeAttribute(1                                              ,'formatVersion'       )
         call file %writeAttribute(char(Formatted_Date_and_Time())                ,'created'             )
         group=file%openGroup('design','The design: the parameters varied, their priors, and the points in parameter space.')
         call group%writeAttribute(countPoints                                    ,'countPoints'         )
         call group%writeAttribute(self%realizationsPerPoint                      ,'realizationsPerPoint')
         call group%writeAttribute(merge(1,0,self%seedPerPoint)                   ,'seedPerPoint'        )
         call group%writeDataset  (names                                          ,'parameterNames'      ,'The name of each parameter.'                                  )
         call group%writeDataset  (self%mappers                                   ,'mappers'             ,'The operatorUnaryMapper class of each parameter.'             )
         call group%writeDataset  (quantiles                                      ,'quantiles'           ,'The prior quantile of each parameter at each design point.'   )
         call group%writeDataset  (values                                         ,'values'              ,'The value of each parameter at each design point.'            )
         priorsGroup=group%openGroup('priors','The prior of each parameter.')
         do j=1,countParameters
            block
              type(hdf5Group) :: priorGroup
              priorGroup=priorsGroup%openGroup(char(var_str('prior')//j))
              call priorGroup%writeAttribute(char(self%priorClasses    (j)),'class'     )
              call priorGroup%writeAttribute(char(self%priorDescriptors(j)),'descriptor')
            end block
         end do
         runsGroup=file%openGroup('runs','The runs of the model: one per realization per design point.')
         call runsGroup%writeDataset(pointIndices                                 ,'pointIndex'          ,'The (zero-based) design point of each run.'                   )
         call runsGroup%writeDataset(realizationIndices                           ,'realizationIndex'    ,'The (zero-based) realization of each run.'                    )
         if (self%seedPerPoint)                                                                                                    &
              & call runsGroup%writeDataset(seeds                                 ,'seed'                ,'The random number seed of each run.'                          )
         call runsGroup%writeDataset(changeFileNames                              ,'changeFileName'      ,'The change file of each run.'                                 )
         call runsGroup%writeDataset(outputFileNames                              ,'outputFileName'      ,'The output file of each run.'                                 )
       end block
       !$ call hdf5Access%unset()
       ! Write the change files.
       if (File_Path(changeFileNames(1)) /= '') call Directory_Make(File_Path(changeFileNames(1)))
       do iRun=1,countRuns
          i=pointIndices(iRun)+1
          open(newUnit=unit,file=char(changeFileNames(iRun)),status='replace',form='formatted')
          write (unit,'(a)') '<?xml version="1.0" encoding="UTF-8"?>'
          write (unit,'(a)') '<!-- Written by the Galacticus `emulatorDesign` task. -->'
          write (unit,'(a)') '<changes>'
          do j=1,countParameters
             ! Values are written with 17 significant figures, sufficient to reproduce them exactly.
             write (valueText,'(es24.16e3)') values(j,i)
             write (unit,'(a)') '  <change type="update" path="'//char(escapeXML(names(j)))//'" value="'//trim(adjustl(valueText))//'"/>'
          end do
          write (unit,'(a)') '  <change type="replaceOrAppend" path="outputFileName">'
          write (unit,'(a)') '    <outputFileName value="'//char(escapeXML(outputFileNames(iRun)))//'"/>'
          write (unit,'(a)') '  </change>'
          if (self%seedPerPoint) then
             write (unit,'(a)'     ) '  <change type="replaceOrAppend" path="randomNumberGenerator/seed">'
             write (unit,'(a,i0,a)') '    <seed value="',seeds(iRun),'"/>'
             write (unit,'(a)'     ) '  </change>'
          end if
          write (unit,'(a)') '</changes>'
          close(unit)
       end do
       message=var_str('wrote design of ')//countPoints//' points ('//countRuns//' runs) to '//self%designFileName
       call displayMessage(message)
    end if
    if (present(status)) status=errorStatusSuccess
    call displayUnindent('Done task: emulator design')
    return

  contains

    function escapeXML(text)
      !!{RST
      Escape characters which may not appear in an XML attribute value.
      !!}
      use :: ISO_Varying_String, only : replace
      implicit none
      type(varying_string)                :: escapeXML
      type(varying_string), intent(in   ) :: text

      escapeXML=replace(text     ,'&','&amp;' ,every=.true.)
      escapeXML=replace(escapeXML,'<','&lt;'  ,every=.true.)
      escapeXML=replace(escapeXML,'>','&gt;'  ,every=.true.)
      escapeXML=replace(escapeXML,'"','&quot;',every=.true.)
      return
    end function escapeXML

  end subroutine emulatorDesignPerform
