!! Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
!!           2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026
!!    Andrew Benson <abenson@carnegiescience.edu>
!!
!! This file is part of Galacticus.
!!
!!    Galacticus is free software: you can redistribute it and/or modify
!!    it under the terms of the GNU General Public License as published by
!!    the Free Software Foundation, either version 3 of the License, or
!!    (at your option) any later version.
!!
!!    Galacticus is distributed in the hope that it will be useful,
!!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!    GNU General Public License for more details.
!!
!!    You should have received a copy of the GNU General Public License
!!    along with Galacticus.  If not, see <http://www.gnu.org/licenses/>.

!+    Contributions to this file made by: Andrew Benson, Claude.

  !!{RST
  Implementation of a posterior state samples class which draws samples from a Sobol sequence in the cumulative distribution of the priors.
  !!}
  
  use :: Numerical_Random_Numbers, only : randomNumberGeneratorClass

  !![
  <posteriorSamples name="posteriorSamplesSobol" docformat="rst">
   <description>
   A posterior state samples class which draws ``[countSamples]`` samples from a Sobol low-discrepancy sequence
   :cite:p:`sobol_distribution_1967` in the cumulative distribution (i.e. the quantiles) of the priors, and maps them to
   parameter values through the inverse of each prior. Such a space-filling design is suitable, for example, as the training
   set for an emulator.

   If ``[randomShift]`` is ``true`` (the default) the design is randomized by a Cranley-Patterson rotation
   :cite:p:`cranley_randomization_1976`: a single random vector, drawn from the ``[randomNumberGenerator]``, is added to every
   point, modulo 1. This preserves the low discrepancy of the sequence while making the design depend on the random seed. In
   this case the design consists of the origin followed by the first :math:`N-1` points of the sequence as generated by GSL
   (which omits the origin), so that when ``[countSamples]`` is a power of two the design is balanced: every one-dimensional
   projection places exactly one point in each interval :math:`[k/N,(k+1)/N)`.

   If ``[randomShift]`` is ``false`` the first :math:`N` points of the GSL sequence are used unchanged. The origin is then
   excluded (as it maps each parameter to the lower limit of its prior, which may be infinite), so the design is not balanced.

   The GSL Sobol sequence supports at most 40 dimensions, and its direction numbers differ from those of some other
   implementations (e.g. SciPy) beyond the second dimension, so designs are not identical to those generated elsewhere.
   </description>
  </posteriorSamples>
  !!]
  type, extends(posteriorSamplesClass) :: posteriorSamplesSobol
     !!{RST
     Implementation of a posterior state samples class which draws samples from a Sobol sequence in the cumulative distribution of the priors.
     !!}
     private
     integer                                      :: countSamples
     logical                                      :: randomShift
     class  (randomNumberGeneratorClass), pointer :: randomNumberGenerator_ => null()
   contains
     final     ::            sobolDestructor
     procedure :: samples => sobolSamples
  end type posteriorSamplesSobol

  interface posteriorSamplesSobol
     !!{RST
     Constructors for the :galacticus-class:`posteriorSamplesSobol` posterior sampling state samples class.
     !!}
     module procedure sobolConstructorParameters
     module procedure sobolConstructorInternal
  end interface posteriorSamplesSobol

contains

  function sobolConstructorParameters(parameters) result(self)
    !!{RST
    Constructor for the :galacticus-class:`posteriorSamplesSobol` posterior sampling state samples class.
    !!}
    use :: Input_Parameters, only : inputParameters
    implicit none
    type   (posteriorSamplesSobol     )                :: self
    type   (inputParameters           ), intent(inout) :: parameters
    class  (randomNumberGeneratorClass), pointer       :: randomNumberGenerator_
    integer                                            :: countSamples
    logical                                            :: randomShift
    
    !![
    <inputParameter docformat="rst">
      <name>countSamples</name>
      <description>
      The number of samples to draw. A power of two gives a balanced design (if ``[randomShift]`` is ``true``).
      </description>
      <source>parameters</source>
      <minimum>1</minimum>
    </inputParameter>
    <inputParameter docformat="rst">
      <name>randomShift</name>
      <defaultValue>.true.</defaultValue>
      <description>
      If true, randomize the design by a Cranley-Patterson rotation (a random shift, modulo 1, applied to every point).
      </description>
      <source>parameters</source>
    </inputParameter>
    <objectBuilder class="randomNumberGenerator" name="randomNumberGenerator_" source="parameters"/>
    !!]
    self=posteriorSamplesSobol(countSamples,randomShift,randomNumberGenerator_)
    !![
    <inputParametersValidate source="parameters"/>
    <objectDestructor name="randomNumberGenerator_"/>
    !!]
    return
  end function sobolConstructorParameters

  function sobolConstructorInternal(countSamples,randomShift,randomNumberGenerator_) result(self)
    !!{RST
    Constructor for the :galacticus-class:`posteriorSamplesSobol` posterior sampling state samples class.
    !!}
    implicit none
    type   (posteriorSamplesSobol     )                        :: self
    integer                            , intent(in   )         :: countSamples
    logical                            , intent(in   )         :: randomShift
    class  (randomNumberGeneratorClass), intent(in   ), target :: randomNumberGenerator_

    !![
    <constructorAssign variables="countSamples, randomShift, *randomNumberGenerator_"/>
    !!]
    return
  end function sobolConstructorInternal

  subroutine sobolDestructor(self)
    !!{RST
    Destructor for the :galacticus-class:`posteriorSamplesSobol` posterior sampling state samples class.
    !!}
    implicit none
    type(posteriorSamplesSobol), intent(inout) :: self

    !![
    <objectDestructor name="self%randomNumberGenerator_"/>
    !!]
    return
  end subroutine sobolDestructor

  subroutine sobolSamples(self,simulationStates,modelParameters_)
    !!{RST
    Generate simulation states from a Sobol sequence in the cumulative distribution of priors.
    !!}
    use :: MPI_Utilities                   , only : mpiSelf
    use :: Numerical_Quasi_Random_Sequences, only : gsl_qrng_sobol, quasiRandomNumberGenerator
    implicit none
    class           (posteriorSamplesSobol     ), intent(inout)                              :: self
    type            (posteriorSampleStateSimple), intent(inout), dimension(:  ), allocatable :: simulationStates
    type            (modelParameterList        ), intent(inout), dimension(:  )              :: modelParameters_
    double precision                                           , dimension(:,:), allocatable :: quantiles
    double precision                                           , dimension(:  ), allocatable :: shift              , stateVector
    type            (quasiRandomNumberGenerator)                                             :: quasiRandomSequence
    integer                                                                                  :: i                  , j          , &
         &                                                                                      countParameters    , iStart

    countParameters=size(modelParameters_)
    allocate(quantiles       (countParameters,self%countSamples))
    allocate(shift           (countParameters                  ))
    allocate(stateVector     (countParameters                  ))
    allocate(simulationStates(                self%countSamples))
    ! Generate the sequence.
    quasiRandomSequence=quasiRandomNumberGenerator(gsl_qrng_sobol,countDimensions=countParameters)
    if (self%randomShift) then
       ! GSL omits the origin from the sequence - restore it as the first point, so that a design of 2^m points is balanced.
       quantiles(:,1)=0.0d0
       iStart        =2
    else
       iStart        =1
    end if
    do i=iStart,self%countSamples
       call quasiRandomSequence%getVector(quantiles(:,i))
    end do
    ! Apply a random shift (a Cranley-Patterson rotation). The shift is drawn on the master MPI process only and summed over
    ! all processes, so that every process constructs the same design.
    if (self%randomShift) then
       shift=0.0d0
       if (mpiSelf%isMaster()) then
          do j=1,countParameters
             shift(j)=self%randomNumberGenerator_%uniformSample()
          end do
       end if
#ifdef USEMPI
       if (mpiSelf%isActive()) shift=mpiSelf%sum(shift)
#endif
       do i=1,self%countSamples
          quantiles(:,i)=modulo(quantiles(:,i)+shift,1.0d0)
       end do
    end if
    ! Convert the cumulative density to a value of the prior.
    do i=1,self%countSamples
       do j=1,countParameters
          stateVector(j)=modelParameters_(j)%modelParameter_%map        (                &
               &         modelParameters_(j)%modelParameter_%priorInvert (               &
               &                                                          quantiles(j,i) &
               &                                                         )               &
               &                                                        )
       end do
       simulationStates(i)=posteriorSampleStateSimple(acceptedStateCount=1)
       call simulationStates(i)%parameterCountSet(countParameters                )
       call simulationStates(i)%update           (stateVector    ,.false.,.false.)
    end do
    return
  end subroutine sobolSamples
