#!/usr/bin/env python3
"""Run and track a campaign of Galacticus models over an emulator design.

The design, and one change file per run, are generated by the Galacticus ``emulatorDesign`` task. This script then
manages the campaign of model runs:

  init      create a campaign manifest from a design file and a base parameter file
  validate  dry-run runs (by default those at the extremes of each parameter) to check them before submission
  run       run pending (or given) runs locally
  submit    submit pending and failed (or given) runs to Slurm as an array job
  status    update and report the status of every run
  resubmit  submit the failed runs again

All commands take the manifest file as their first argument. See the "Emulator-Assisted Calibration" chapter of the
user guide.

Andrew Benson, Claude (23-September-2026).
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.join(os.environ.get('GALACTICUS_EXEC_PATH', '.'), 'python'))

from Galacticus.Emulation.campaign import Campaign  # noqa: E402


def _indices(text):
    """Parse a list of run indices, e.g. `0,3,5-7`."""
    if text is None:
        return None
    indices = []
    for part in text.split(','):
        if '-' in part:
            first, last = part.split('-')
            indices.extend(range(int(first), int(last) + 1))
        else:
            indices.append(int(part))
    return indices


def _report(campaign):
    summary = campaign.summary()
    print('  '.join(f'{status}: {count}' for status, count in sorted(summary.items())))
    for run in campaign.select(statuses=('failed',)):
        print(f'  run {run.index} (point {run.point}, realization {run.realization}) failed: {run.message} [log: {run.log_file}]')


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split('\n\n')[0], formatter_class=argparse.RawDescriptionHelpFormatter)
    subparsers = parser.add_subparsers(dest='command', required=True)

    parser_init = subparsers.add_parser('init', help='create a campaign manifest')
    parser_init.add_argument('manifest')
    parser_init.add_argument('--design', required=True, help='the design file written by the emulatorDesign task')
    parser_init.add_argument('--base', required=True, help='the base parameter file for every run')
    parser_init.add_argument('--executable', help='the Galacticus executable (default: $GALACTICUS_EXEC_PATH/Galacticus.exe)')
    parser_init.add_argument('--logs', help='the directory for run logs (default: a `logs` directory alongside the change files)')
    parser_init.add_argument('--overwrite', action='store_true', help='replace an existing manifest')

    parser_validate = subparsers.add_parser('validate', help='dry-run runs to check them before submission')
    parser_validate.add_argument('manifest')
    parser_validate.add_argument('--runs', help='runs to validate, e.g. `0,3,5-7` (default: the runs at the extremes of each parameter)')
    parser_validate.add_argument('--all', action='store_true', help='validate every run')
    parser_validate.add_argument('--parallel', type=int, default=1, help='the number of dry runs to make at once')

    parser_run = subparsers.add_parser('run', help='run pending (or given) runs locally')
    parser_run.add_argument('manifest')
    parser_run.add_argument('--runs', help='runs to run, e.g. `0,3,5-7` (default: all pending or failed runs)')
    parser_run.add_argument('--parallel', type=int, default=1, help='the number of runs to make at once')
    parser_run.add_argument('--threads', type=int, help='OpenMP threads per run')

    for name, help_text in (('submit', 'submit pending and failed (or given) runs to Slurm'), ('resubmit', 'submit the failed runs again')):
        subparser = subparsers.add_parser(name, help=help_text)
        subparser.add_argument('manifest')
        if name == 'submit':
            subparser.add_argument('--runs', help='runs to submit, e.g. `0,3,5-7` (default: all pending or failed runs)')
        subparser.add_argument('--partition', help='the Slurm partition (default: from galacticusConfig.xml)')
        subparser.add_argument('--walltime', help='the walltime of each run, e.g. `40:00:00`')
        subparser.add_argument('--cpus', type=int, help='CPUs (and OpenMP threads) per run')
        subparser.add_argument('--memory', type=int, help='memory per run, in MB')

    parser_status = subparsers.add_parser('status', help='update and report the status of every run')
    parser_status.add_argument('manifest')

    args = parser.parse_args(argv)

    if args.command == 'init':
        campaign = Campaign.create(args.manifest, args.design, args.base, executable=args.executable,
                                   log_directory=args.logs, overwrite=args.overwrite)
        print(f'created campaign of {len(campaign.runs)} runs in {args.manifest}')
        return 0

    campaign = Campaign.load(args.manifest)

    if args.command == 'validate':
        indices = [run.index for run in campaign.runs] if args.all else _indices(args.runs)
        results = campaign.validate(indices=indices, parallel=args.parallel)
        failures = [result for result in results if not result.ok]
        for result in failures:
            print(f'run {result.run}: {result.message}')
        print(f'validated {len(results)} runs: {len(results) - len(failures)} passed, {len(failures)} failed')
        return 1 if failures else 0

    if args.command == 'run':
        campaign.run_local(indices=_indices(args.runs), parallel=args.parallel, threads=args.threads)
        _report(campaign)
        return 0

    if args.command in ('submit', 'resubmit'):
        import queueManager
        options = {}
        if args.walltime is not None:
            options['walltime'] = args.walltime
        if args.cpus is not None:
            options['cpusPerTask'] = args.cpus
            options['countOpenMPThreads'] = args.cpus
        if args.memory is not None:
            options['memory'] = args.memory
        indices = _indices(args.runs) if args.command == 'submit' else [run.index for run in campaign.select(statuses=('failed',))]
        if args.command == 'resubmit' and not indices:
            print('no failed runs to resubmit')
            return 0
        job_id = campaign.submit(queueManager.factory(args), indices=indices, job_options=options)
        if job_id is None:
            print('no runs to submit')
        else:
            print(f'submitted array job {job_id}')
        return 0

    if args.command == 'status':
        campaign.refresh()
        _report(campaign)
        return 0

    return 1


if __name__ == '__main__':
    sys.exit(main())
