!! Copyright 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018,
!!           2019, 2020, 2021, 2022
!!    Andrew Benson <abenson@carnegiescience.edu>
!!
!! This file is part of Galacticus.
!!
!!    Galacticus is free software: you can redistribute it and/or modify
!!    it under the terms of the GNU General Public License as published by
!!    the Free Software Foundation, either version 3 of the License, or
!!    (at your option) any later version.
!!
!!    Galacticus is distributed in the hope that it will be useful,
!!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!!    GNU General Public License for more details.
!!
!!    You should have received a copy of the GNU General Public License
!!    along with Galacticus.  If not, see <http://www.gnu.org/licenses/>.

!!{
Contains a program to test features of cryptographic hashes.
!!}

program Test_Hashes_Cryptographic
  !!{
  Contains a program to test features of cryptographic hashes.
  !!}
  use :: Display             , only : displayVerbositySet, verbosityLevelStandard
  use :: Hashes_Cryptographic, only : Hash_MD5
  use :: ISO_Varying_String  , only : assignment(=)      , char                  , varying_string
  use :: Unit_Tests          , only : Assert             , Unit_Tests_Begin_Group, Unit_Tests_End_Group, Unit_Tests_Finish
  implicit none
  type(varying_string) :: myHash, myText

  ! Set verbosity level.
  call displayVerbositySet(verbosityLevelStandard)
  ! Begin unit tests.
  call Unit_Tests_Begin_Group("Cryptographic hashes")
  ! Hash a simple phrase and compare the result with the hash generated by Perl's Crypt::PasswdMD5
  ! module.
  myText="dolphin monkey badger marmoset"
  myHash=Hash_MD5(myText)
#include "os.inc"
#ifdef __APPLE__
  call Assert("MD5 hash [c.f. Perl Crypt::PasswdMD5]",char(myHash),"xsKIRXZS.dU"           )
#else
  call Assert("MD5 hash [c.f. Perl Crypt::PasswdMD5]",char(myHash),"4ZAhhB6m4Wn7TCccmTKAc@")
#endif
  ! End unit tests.
  call Unit_Tests_End_Group()
  call Unit_Tests_Finish   ()

end program Test_Hashes_Cryptographic
