name: Link-Check
on:
  workflow_dispatch:
  schedule:
    - cron: '32 13 * * *'
permissions:
  contents: read
jobs:
  Check-Links:
    runs-on: ubuntu-latest
    concurrency:
      group: checklinks-${{ github.ref }}
      cancel-in-progress: true
    env: 
      adstoken: ${{ secrets.NASA_ADS_API_TOKEN }}
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server."
      - run: echo "The name of the branch is ${{ github.ref }} and the repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: "Set environmental variables"
        run: |
          echo "GALACTICUS_EXEC_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Cache dynamically-generated datasets
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ${{ github.workspace }}/linkCheckFailures.xml
          key: linkCheckFailures-${{ github.run_id }}
          restore-keys: |
            linkCheckFailures
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.x'
      - name: Install tools
        run: |
           python -m pip install --upgrade pip
           pip install requests lxml
      - name: Check for broken links
        if: ${{ env.adstoken != '' }}
        id: check_links
        continue-on-error: true
        run: |
          cd $GALACTICUS_EXEC_PATH
          git config --global --add safe.directory $GALACTICUS_EXEC_PATH
          ./scripts/aux/linkChecker.py ${{ secrets.NASA_ADS_API_TOKEN }} badURLs.md
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3
        with:
          files: badURLs.md
      - name: Output to a job summary
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          cat badURLs.md >> $GITHUB_STEP_SUMMARY
      - name: Report job failure if broken links were found
        if: steps.check_links.outcome == 'failure'
        run: |
          echo "Broken links found - marking the job as failing."
          exit 1
